version: '3'
services:
  atlas-build:
    build:
      context: .
      dockerfile: Dockerfile.atlas-build
    image: atlas-build
    container_name: atlas-build
    hostname: atlas-build.example.com
    stdin_open: true
    tty: true
    networks:
      - atlas
    volumes:
      - ~/.m2:/home/atlas/.m2
      - ./scripts:/home/atlas/scripts
      - ./patches:/home/atlas/patches
      - ./dist:/home/atlas/dist
    depends_on:
      - atlas-base
    environment:
      BRANCH: 'master'
      SKIPTESTS: 'true'
      PROFILE: 'dist,berkeley-solr'

networks:
  atlas:
